# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b35d1f9679c7539051d3760e6198a3cfe200f3774dbb9f970c95bd633bbb147d25ae3ce746f0b93493a649f2bb97089925a4b28f3989c69a1f9d05003c65b0f

test:
  secret_key_base: 1dc4adc4439d71dcf718ef4ad1cc2ae9d0599614f79d2ec635de9a4cd4036b4bb0cb99b4a05c6e46ec812ddd05cb2b23110f32eef4e03d83759b904d4630737b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
